spring:
  application:
    name: backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: user
    password: login!234

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: 4McT13rVLmAKTVvleSz1
            client-secret: xXJXMdq1nW
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email
#          google:
#            client-name: google
#            client-id:
#            client-secret:
#            redirect-uri: http://localhost:8081/login/oauth2/code/google
#            authorization-grant-type: authorization_code
#            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

server:
  port: 8081
